name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa todos os dias à meia-noite
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: Matthew-456
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg

      - name: Enviar resultado para o repositório
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: snake
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
